### ISSUE TITLE
Error in db account creation

### ISSUE THREAD

**Issue by Naman794** [jaypey/gcoinbot#5]
Client table is missing, which is not letting the user create account
![unknown (12)](https://user-images.githubusercontent.com/65483393/148368912-dd528b65-f416-47c9-b9dc-f0f13ee4e809.png)

**Comment by jpbelval** [comment]
Hi,

The bot requires an sqlite3 database with the Client table to work.

In the command line in the same directory as confi.py, type `sqlite3 coin.db`, it will create the database.

Then, copy the following sql script in a .txt file (same directory):

```
CREATE TABLE "Clients" (
	"id"	INTEGER NOT NULL,
	"client_name"	varchar(255) NOT NULL,
	"balance"	int,
	"last_daily"	varchar(255),
	PRIMARY KEY("id")
)
```

To add the table to the database, just type `.read <yourtextfile>.txt` while in sqlite3.

It should work after that, you can also confirm the table has been created by using `.tables` which lists all the existing tables from the database.

**Comment by Naman794** [comment]
understood thanks for the reply!✌
