### ISSUE TITLE
bot not working here is the error

### ISSUE THREAD

**Issue by yerkovlad** [jaypey/gcoinbot#7]
Traceback (most recent call last):
  File "E:\venv\Lesson\venv\mysever\gcoinbot-master\gcoinbot-master\confi.py", line 10, in <module>
    with open('config.json') as config_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by jpbelval** [comment]
config.json is a file not included in the repository that you must create for the bot to work.  The file has the following format:
`{
        "token": "YOUR_TOKEN_HERE"
}
`
Simply create the file and put it in the same directory as the py script.
